name: MacOS

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install CMake
        run: brew install cmake

      - name: Install Catch2
        run: brew install catch2

      - name: Install Qt6
        run: brew install qt@6

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_PREFIX_PATH="$(brew --prefix qt@6)"

      - name: Build Project
        run: cd build && cmake ..

      - name: Test
        run: cd build && make tests &&  cd test && ./tests
